
const char* kKickstarterNames[] = {
"!Tulingen", "2Awesome Studio", "404 Name Not Found", "A. N.", "AGKBYDKI", 
"AMRIV", "Aaron", "Aaron A. Reed", "Aaron Christopher Magabo", "Aaron Dykstra", 
"Aaron Gable", "Aaron Kaluszka", "Aaron St.John", "Aaron strohmeier", "Abraham Chan", 
"Abraham Heidebrecht", "Adam Finlayson", "Adam P", "Adam Rajski", "Adam Rogers", 
"Adam Shale", "Adam Truncale", "Adam Veit", "Adam Walker", "Adam Walker Studio", 
"Adam Ziegler", "Adrian Aw-Young", "Adrian Keyes", "Adriano Petrich", "AeKae", 
"Aemulari", "Aerouge", "Aguhsth Ygdemo Bröstbom", "AhTtekan", "Aidan Bell", 
"Ajay Tirumala", "Akule", "Alan", "Alan Cohen", "Alan Lucas", 
"Alan Rowarth", "Alan Szymkowiak", "Alastair Bloomfield", "Albert", "Alberto Haviola", 
"Albertus Valentyn", "Alden Horowitz", "Aleksandar Odorović", "Alex", "Alex Banov", 
"Alex Bartho", "Alex De Young", "Alex Jackson", "Alex Rito", "Alex Solo", 
"Alex Thomas", "Alex Turner", "Alex Turnpenny", "Alex Welsh", "Alex Wilkinson", 
"Alex Xie", "Alexander", "Alexander Evans", "Alexander Gardner", "Alexander K", 
"Alexander Krasij", "Alexander Pronchenkov", "Alexander Pullman", "Alexander Teoh", "Alexander Trimble", 
"Alexander Welk", "Alexander Womack", "Alexandre Duvivier", "Alexandre Fafard", "Alexandre Lautié", 
"Alexandre Lima Dos Santos", "Alexandre Sapata Carbonell", "Alexandre van Chestein", "Alexey  Imansu", "Ali Harrison", 
"Alisha Thayer", "Alistair Collins", "Alkxzv", "Allan Daugherty", "Allan Kilpatrick", 
"Allison Paschke", "Allyn", "Amanda D'Avria", "Ameer Tavakoli", "Amy Robson", 
"An0n", "Anders Findal Jørgensen", "Andre", "Andre Bernier", "Andreas Enge", 
"Andreas Halbakken Sundby", "Andreas Huber", "Andreas Kjelgaard", "Andreas McDermott", "Andrew", 
"Andrew Behm", "Andrew Bishara", "Andrew Butler", "Andrew Ceballos", "Andrew Cook", 
"Andrew Croftcheck", "Andrew Curtis", "Andrew Danner", "Andrew Gray", "Andrew Haufe", 
"Andrew Henninger", "Andrew Li", "Andrew Metz-White", "Andrew Petersen", "Andrew Sarkarati", 
"Andrew Shouldice", "Andrew Skippon", "Andrew Speer", "Andrew Styles", "Andrew V", 
"Andrew Wardle", "Andrew Wilson", "Aniq Ahmad", "Anthony", "Anthony Fullmer", 
"Antoine Lévesque", "Anton", "Anwar Ariffin", "Archibald JEGO", "Ari Schumer", 
"Arie Hofland", "Arnaud", "Arthur Peters", "Artur Andrzejewski", "Astfgl66", 
"Aubrey Hayashida", "Austen Higgins-cassidy", "Austin Stone", "Austin Warawa", "Average Gamer", 
"Axerox", "Aymen Hamid", "BJ Tomiko", "BK", "Babarix", 
"Backer Name", "Bad_Syntax", "Bailey Symonds", "Balthazar", "Balthazar Newgate", 
"Banjamin Bo", "Banzai", "Bart Enkelaar", "Bartholomew Gibson", "BarxBaron", 
"Basil Chen", "Bastiaan Grutters", "Bastian Hoyer", "Bastic", "BattleFate", 
"Beau Gunderson", "Becoming", "Beefok", "Ben", "Ben Banton", 
"Ben Engelsberg", "Ben Gray", "Ben Hartman", "Ben Hesketh", "Ben Holleran", 
"Ben Kelly", "Ben Mihill", "Ben Pielstick", "Ben Prunty", "Ben Reis", 
"Ben Smith", "Ben Stevens", "Benjamin Myers", "Benjamin Philippe", "Benjamin Remond", 
"Bert Capuano", "Bjoern Olde", "Björn Morén", "Black", "Black Blade", 
"BlackMagicM66", "Blacky", "Blair McKenzie", "Blair Nicholson", "Blake Conrad Magee", 
"Blarghedy", "Bo Goeran Kvamme", "Boneville", "Bouzekri", "Brad", 
"Brad Celski", "Brad Devlin", "Brad Dragun", "Brad Wilson", "Braden", 
"Brandon", "Brandon Bubnich", "Brandon K", "Brandon Lee", "Brandon Riegel", 
"Brandon Singer", "Brendan G Conway", "Brendan Trayner", "Brenden Bissett", "Brent Barker-Miller", 
"Brent Iliffe", "Brett Hill", "Brett Levy", "Brian", "Brian Anderson", 
"Brian Edward Rodgers", "Brian Ellis", "Brian Johnston", "Brian Marks", "Brian May", 
"Brian O'Neill", "Brian Robbins", "Brian Rubin", "Brian Soule", "Brian Weisberg", 
"Brooks Brown", "BruceP - Sheriff of Phoenix Rising", "Bruno De Angeli", "Bruno Serra Loff Barreto", "Bruski", 
"Bryan Lott", "Bryan Mytelka", "CF", "Cabel", "CadenzaForte", 
"Cale", "Caleb Gingles", "Callum Stock", "Calvin Moss", "Cam Pursel", 
"Cameron", "Cameron Adams", "Candy Bilyk", "Carakav", "Cardboard Fortress Games", 
"Carnell J. Durant", "Carolyn VanEseltine", "Carter Reece", "Carter Rogness", "Casey B Smith", 
"Cash Garman", "Cassady Roop", "Cats777", "Cervator", "Chad Carlton", 
"Chais Orgill", "Chandler", "Charles Brown", "Charles Burlington", "Charles Motyka", 
"Charles Snyder", "Charles Stutz", "Charles Todd Gwynn", "Chase Cummings", "Chen Shin-Jih", 
"Chevsay", "Chip Simmonds", "Choi Yeonho", "Chris", "Chris Barrett", 
"Chris Bell", "Chris Beyer", "Chris Castaldi", "Chris Gibson", "Chris Green", 
"Chris Hamilton", "Chris Horii", "Chris Horton", "Chris Johnson", "Chris Macgregor", 
"Chris Milne", "Chris Ocano", "Chris Phillips", "Chris Stephens", "Chris Volcheck", 
"Chris W", "Christian", "Christian Leis", "Christian Vogel", "Christine H.", 
"Christoph Scott Williams", "Christopher A Grove", "Christopher Grame", "Christopher Haney", "Christopher Hasouros", 
"Christopher Lee", "Christopher Lewis", "Christopher Macpherson", "Christopher Martin", "Christopher Martin Richardson", 
"Christopher Neal", "Christopher Palumbo", "Christopher Paul", "Christopher Reed", "Christopher Smith", 
"Christopher Stoll", "Christopher Tremblay", "Christopher Weeks", "Chuck Byers", "Ciaran P", 
"Claive Ver. 5.16", "Clarence Johnson", "Clayton @ Laboratory", "Cle", "Clemens Niemeyer", 
"Clyde Wilson", "CodGod", "Colin", "Colin Arnoldus", "Colin Huang", 
"Colin Smith", "Conan Reis", "Connie Moresco Leach", "Connor Smith", "Conor", 
"Cornflakes", "Corwin Dodd", "Cory Feil", "Cory Harbak", "Cory Jones", 
"Cory Ziolkowski", "Craig  Swain", "Craig Alexander Dolan", "Craig Littler", "Craig Mackie", 
"Cristie Munoz", "Curtis Yager", "D'Arc Whitman", "D. Moonfire", "Daeho Seo", 
"Dale", "Daljit Chandi", "Damien Grimard", "Dan Carlisle", "Dan Dixon", 
"Dan Hope", "Dan Morenus", "Dan Salenger", "Dan Weiss", "Dana Mongillo", 
"Daniel", "Daniel Berke", "Daniel Brauer", "Daniel Burrage", "Daniel Dearing", 
"Daniel Drexler", "Daniel Fridley", "Daniel Geuss", "Daniel Hall", "Daniel Johnson", 
"Daniel M. Kane", "Daniel Milger", "Daniel Notthoff", "Daniel Ryan", "Daniel Staub", 
"Daniel Steel", "Daniel T Lemich", "Daniel Uzunow", "Daniel Wagner", "Daniel West", 
"Daniel Wolfe", "Danny Piccione", "Dargon", "Darin Clark", "Daryl Egg Edge", 
"Dave", "Dave Kin", "Dave Velho", "David", "David Albert", 
"David Allen the Second", "David Ballard", "David Bonnie", "David Brittain", "David Bukowski", 
"David Camp", "David Curry", "David GIannetto", "David Harron", "David Heyman", 
"David Isaac Frohman", "David Kirtley", "David Lee Seymour", "David Osivnik", "David R", 
"David Reeves", "David Riedel", "David Ryan", "David Solomon Fall", "David Ting", 
"David Tse", "David White", "David cunnington", "David.Schöler", "Dayna", 
"DeWulff", "Dean Thrasher", "Deceleration", "Delibean", "Delve Interactive", 
"Dennis Chen", "Dennis Duwe the Haribokid", "Dennis Fanshaw", "Dennis Holm", "Deoxys114", 
"Derek K Harwell", "Derek Lynch", "Derek Robertson", "Desertification", "Devin Dubin", 
"Dewey Yang", "Dexther", "DifferentName", "DigitalStef", "Dillyo09", 
"Dinsdale1978", "Dom", "Domad", "Dominik Badawi", "DongGun Kim", 
"Donkey Crew", "DoomSayerSantos", "Dorian Stefan Bucur", "Doug", "Doug Schnur", 
"Douglas Carter", "Drain", "Dranolix", "Dreadbit", "Drenix", 
"Drew Blas", "Drew Peterson", "Duartel", "Duncan Barber", "Duncan Laurie", 
"Duncan Riach", "Dustin Green", "Dustin Walton", "Dylan Gray", "ERICdb", 
"Ean Moody", "Earl Adams", "Eben du Toit", "Ebyan Alvarez-Buylla", "Eddie Churchill", 
"Eddie Lee", "Edgar Chicas", "Edmond Meinfelder", "Edmund Tang", "Edoz", 
"Edward Benjamin Hunter", "Edward Kasch", "Edward Olive", "Edward Shackcloth", "Ege Kurdas", 
"Eileen LaBoone", "Eli Omernick", "Elias23", "Emanresu", "Emanuel", 
"Emily", "Emily Bua", "Emmanuel Aranha", "Enzo Martin", "EraZorX", 
"Eran Galperin", "Eric", "Eric Charlton", "Eric Eshleman", "Eric Knudson", 
"Eric Loeffler", "Eric Lutley", "Eric Nolan", "Eric Olson", "Eric Phillips", 
"Eric Roy", "Erich Cooper", "Erik", "Erik Andreassen", "Erik Hefflefinger", 
"Ethan Bell", "Ethan Hedman", "Ethan Jason Holly", "Eugene Kim", "Ev1lmonk3y1223", 
"Evan", "Evan Anderson", "Evan Cooney", "Everix", "Evgeny Andreeshchev", 
"ExiFox", "Fabio Bertuzzi", "Felipe", "Felipe De Castro Cruz", "Felix Moser", 
"Fenris", "Fergus Conolly", "FerrousFox", "Firebelly Studios", "Flare Choo Chin Mun", 
"Flarehawk", "FlipskiZ", "Forest Willard", "Francois Langelier", "Frank Ayre", 
"Frank Mangelschots", "Frank Verhage", "Fred Stober", "Frederick Angstadt", "Fredrik Holmqvist", 
"Fringale", "Fringe Games", "G. Assies", "GaLm", "Gabriel Freiman", 
"Gabriel Sibley", "Gage Kotze", "Galious", "Galomtala", "Gareth", 
"Gareth Hughes", "Gareth Martin", "Garou", "Garret Reece", "Gary Achenbach", 
"Gary Don O'Geralds", "Gary Isaac", "Gary Poon", "Gavan", "Gazz", 
"Geoffrey McGrew", "George Albany", "George Chen", "George Lambrakis", "George Leach", 
"George Richardson", "George Wilkins", "Georgy", "Gerald Cameron", "Gergő Kopácsi", 
"Geronico", "Gerrit Kaul", "Giacomo Russo", "Gillingham", "Gordon Tran", 
"Gr4vity", "Graham Cobb", "Graham McGibbon", "Grant", "Grant Merrill", 
"Greer Greer", "Greg", "Greg Batha", "Greg Chase", "Greg Kovas", 
"Greg Sienkiewicz", "Gregg Tavares", "Gregory Adam Conroy", "Greyson Wolfe", "GruensFroeschli", 
"Guy Peled", "H. Elwood Gilliland III", "HARD N DA PAINT", "Hach", "Haevermaet Anthony", 
"HalfBus", "Hannes Rosner", "HappyWulf", "Hardenberg", "Harley", 
"Harri Pyykkö", "Harrison LK", "Heath Higgins", "Henrik Aasted Sørensen", "Henry Cohen", 
"Hero Forge", "Hidetoshi Inoue", "Hieu", "Hilton Devitt", "Hoflog", 
"Holden Link", "Holger Ludvigsen", "Horace", "Howling Moon Software", "Hrvoje Butkovic", 
"HunTurkey", "Hunter Barrington", "Hunter Harris", "HypnoticSheep", "Håkon Sagen", 
"IGOR CRUZ PINTO CORREIA", "Ian Andersen", "Ian Burgmyer", "Ian Cockburn", "Ian Dees", 
"Ian Grossberg", "Ian Koxvold", "Ian Kragh", "Ian Scott", "Ian Wilbanks", 
"Igor Wiedler", "Imad", "Infamy Miniatures", "Ingo Devooght", "Ingolf Kramer", 
"Isaac", "Isac Zamora", "Ivan Ramones", "Ivar U Nikolaisen", "J.P. Brichta", 
"JC", "JP Miller", "JWNoctis", "Jaakko Konttinen", "Jabberwok", 
"Jacco van Weert", "Jack Morrison", "Jack Thompson", "Jackie Yang", "Jaco du Preez", 
"Jacob", "Jacob Dubois", "Jacob K.", "Jacob Mandell", "Jacob Maskiewicz", 
"Jacob Schafer", "Jacob Spjut", "Jacob Wood", "Jacsebalon", "Jago", 
"Jaime Ivan Zavala-Basurto", "Jake Crankshaft", "Jakub Kyncl", "James", "James Bolton", 
"James Buckhorn", "James Cobb", "James Crossley", "James Franks", "James Gliwa", 
"James Lucas", "James Mason Pierce", "James Mills", "James Orzechowski", "James Peebles", 
"James Ramirez", "James Schultz", "James Sims", "James Slade", "James Surine", 
"James T Woods", "James Weeks", "Jamesac68", "Jan Henning Peters", "Jan Paulsson", 
"Jardine", "Jared", "Jarno Raula", "Jaron", "Jason", 
"Jason Attard", "Jason Denney", "Jason Nollan", "Jason Ong", "Jason Raynor", 
"Jason Tampake", "Jason Znack", "Jasper", "Jay", "Jay Bushey", 
"Jay Eastaugh", "Jay Lemmon", "Jc Theunpleasant", "Jean-François Marck", "Jean-Marie Prevost", 
"Jed Lawnsby", "Jed Moore", "JediMaster", "Jedidiah Esposito", "Jef Bell", 
"Jeff Hoffman", "Jeff Houde", "Jeff Klepper", "Jeff Sans", "Jeffrey", 
"Jeffrey Lin", "Jeffrey Meyer", "Jeiro Coste", "Jekotia", "Jennifer McMahon", 
"Jenny & Chris", "Jens Rivenes", "Jens Rupp", "Jeremiah Ingham", "Jeremiah McNicholas", 
"Jeremiah Zinn", "Jeremy", "Jeremy Barber", "Jeremy Guiles", "Jeremy Haney", 
"Jeremy Joseph Covington", "Jeremy Kennedy", "Jeremy Mayer", "Jeremy Miller", "Jerry A Segler, Jr.", 
"Jerry Ozbun", "Jerry Winkler", "Jess", "Jesse McIntyre", "Jesse Roberts", 
"Jessica Bondy", "JesusFreke", "Jez", "Jezariael Demos", "Jim Ellis", 
"Jim Wall", "Jimmy Trimble", "Jin ", "Jiri", "Joan Recasens", 
"Joe", "Joe Fusion", "Joe Jaquette", "Joel", "Joel Cruz", 
"Joel Pelina", "Johan Coen", "Johannes", "Johannes Kommer", "John", 
"John Allen", "John Alvarado", "John Danskin", "John Eddy", "John Evans", 
"John Gaffney", "John Henry McMills Warrington", "John Jolly", "John Kiniston", "John Lofstrom", 
"John McNabb", "John Robertson", "John Sitar", "John Tynefield", "John Wilson", 
"John Yeier", "John di Battista", "Johnathan M. Couitt", "Johnathan Munroe", "Johnathan Tarr", 
"Johnathon Opstad", "Johnny Go-Time", "Johnny Jigglefist", "Jon", "Jon Baker", 
"Jon Benny Benson", "Jon Buran", "Jon E Bordoy", "Jon Lee", "Jon Pluck", 
"Jon Ramsell", "Jonas Madsén", "Jonas Nilssen", "Jonathan", "Jonathan Crumley", 
"Jonathan Dallas", "Jonathan Hoang", "Jonathan Kerry", "Jonathan Niehof", "Jonathan Pelchat", 
"Jonathan Shaver", "Jonathan Turpie", "Jonathan Waldo", "Jonathan43551", "Jonathon Payne", 
"Jonny James", "Jordan Ambridge", "Jordan Felle", "Joseph A Parker", "Joseph Castellat", 
"Joseph Ferrier", "Joseph Poultney", "Josh Hash", "Josh King", "Josh Look", 
"Josh Parnell", "Josh Williams", "JoshParadroid", "Joshua Allen Pinckney", "Joshua Beale", 
"Joshua Benedetto", "Joshua Carmody", "Joshua Edge", "Joshua Megerman", "Joshua Miller", 
"Joshua Ross-Daly", "Joshua Sprague", "Joshua hawkins", "Joziser", "Juan Gomez", 
"Judd Gledhill", "Juergen Stockhaus", "Juho", "Jul", "Julian", 
"Julian Norton", "Julien Roncaglia", "Julio Cesar Vasconcellos", "Jupiter Jazz", "Justin", 
"Justin Akkerman", "Justin Barker", "Justin Landry", "Justin Parra", "Justin S", 
"Justin Simonson", "Justin Stoermer", "Justin Yeo", "K Cullen", "KUNIHIKO OZAKI", 
"Kaamio", "Kai", "KaiserDuGarde", "Kanthes", "Kapah", 
"Karan Buasakdi", "Karitmiko", "Karl Wortmann", "Kasper Aae", "Kasper Brohus Allerslev", 
"Kat McKay", "Katorone", "Katt Forge", "Keanan", "Keegan Farley", 
"Keiran", "Keith Bradner", "Keith Olson", "Keith Thomson", "Keith White", 
"Kelduum Revaan", "Ken N.", "Ken Nakai", "Ken Wickle", "Kendall Nelson", 
"Kenneth Larsen", "Kenneth Lewis", "Kevin Allen", "Kevin Bisbing", "Kevin Brinck", 
"Kevin Brown", "Kevin Davies", "Kevin J", "Kevin Kortekaas", "Kevin Kwong", 
"Kevin Modzelewski", "Kevin Monkhouse", "Kim Grønbek", "Kimberly Burgess", "Kin Sum", 
"Kirk Iles", "Koda", "Kory Law", "Kossimer", "Krish Shrikumar", 
"Kristin Edwards", "Kristina Durivage", "Kristoffer Domanski", "Krypt", "Kuniaki Watanabe", 
"Kurt Heinecke", "Kurt K", "Kyle Dohring", "Kyle Halvorson", "Kyle Hitchcock", 
"Kyle LaBonte", "Kévin Cardoso de Sá", "LL", "Lachlan Kearns", "Lance Edwards", 
"Lane Holloway", "Larry Lipsmeyer", "Lars-Mikael Skov Birlø", "LastAndroid", "Laura Borgen", 
"Laura LeBlanc", "Laurence Gonsalves", "Laven Pillay", "Le_Gambit", "Lee Smart", 
"Lee Tewksbury", "Lee Williams", "Legione", "Leigh Jevon", "Leland Gregory", 
"Leo Browning", "Leo Clark", "Leon Hong", "Leslie Taylor", "Liam Griffiths", 
"Liam Kennedy", "Lim Kim Yong", "Lin Junyu", "Linhart Walter", "Lionel Belen", 
"Lixxx235", "Lloyd Fitzroy-Smith", "Logan", "Logan Godkin", "Lol nope", 
"Loren Chorley", "Lost Demiurge", "Lost Question", "Lucas Barrie", "Lucas Siqueira", 
"Luis Goyzueta", "Luis William Olivieri", "LukasM", "Luthorne", "Lyton Darque", 
"M- H-", "M@", "Mabel Loveall", "MacDaniels", "MachineMk2", 
"Mads G.", "Magikchicken", "Magnus", "Magnus528", "Majid Al-Qassimi", 
"Malaak", "Malcolm Gin", "Manawind", "Marc Rau", "Marco Sebazco", 
"Marco Túlio Costa", "Marcus Allen Nichols (Miyordon)", "Marcus Gipps", "Marcus Kraus", "Marcus Storey", 
"Marek Opłotny", "Marieke", "Mario Roberti", "Marjie", "Mark", 
"Mark Barr", "Mark Campos", "Mark Grey", "Mark Gutman", "Mark Henning", 
"Mark Kadas", "Mark Papageorge", "Mark Pedersen", "Mark Rowe", "Mark Shocklee", 
"Mark Smith", "Marlon Mapstone", "Martin", "Martin Cathrae", "Martin Galese", 
"Martin Steers", "Martin Sugianto", "Martin Walker", "Mary Risseeuw", "Masataka Okihara", 
"Masochist", "MasterFu", "Mathias", "Matt", "Matt DiBernardo", 
"Matt K", "Matt Keeter", "Matt Parisi", "Matt Saylor", "Matt Sheckells", 
"Matt Shipps", "Matthew", "Matthew C Tran", "Matthew Cisneros", "Matthew Essig", 
"Matthew Green", "Matthew Henley", "Matthew Jensen", "Matthew Lim", "Matthew Lucas", 
"Matthew Marshall", "Matthew McDonald", "Matthew Moskewicz", "Matthew Richard", "Matthew Sanders", 
"Matthew Sayers", "Matthew Shepard", "Matthew Spaulding", "Matthew Stender", "Matthew Wetzel", 
"Matthew Z Haralovich", "Matthew Ziegelbaum", "Matti Mustajärvi", "Mattias Lederer", "Mattk50", 
"Mauro Steinn", "Max", "Max Edward Lockyer", "Max Juchheim", "Max Kingsbury", 
"Max Langhof", "Max Loy", "Max Metcalf-Putnam", "Maxim Mendelson", "Maxime Wielemans", 
"Maxwell Jacob", "Maxwell Neely-Cohen", "Memnarch", "MeowPuff Games", "Miauw", 
"Michael", "Michael Bock", "Michael Corrigan", "Michael Davis", "Michael Duffy", 
"Michael Glombicki", "Michael Griffiths", "Michael House", "Michael Langer", "Michael Leng", 
"Michael Leuthaeuser", "Michael Renz", "Michael Riccio", "Michael Skolnik", "Michael Snyder", 
"Michael Townsend", "Michael Truncale", "Michael Twomey", "Michael Wildermoth", "Michal Gloc", 
"Michaël Oversteyns", "Michel Kayser", "Mick Darling", "Mikael Dahlberg", "Mike", 
"Mike Brown", "Mike D", "Mike Danger Donaghey", "Mike Firestack", "Mike Frey", 
"Mike L", "Mike Overhill-Smith", "Mike Stipicevic", "Mike Warren", "Mikhail", 
"Miles", "Miles Fitzpatrick", "Miles Morse", "Milo", "Minsc&Boo", 
"Mitchell Christov", "Mithra", "Miyakawa Yoshiharu", "MonsieurLeSlug", "Motiejus Osipovas", 
"Mrgagarin29", "Mushroomxman", "Myles Fowler", "Mystify", "ND356", 
"NZ", "Nahere", "Naram Qashat", "Nat Blundell", "Nat Schwartz", 
"Nate Schmold", "Nathan A Newsad", "Nathan D Howell", "Nathan Eberhart", "Nathan Fritz", 
"Nathan Harling", "Nathan Pinnow", "Nathan Ringo", "Nathaniel O'Neill", "Nathaniel Troutman", 
"Neil Fortune", "Neil Harkins", "Neil Stalker", "Nelson", "Nevera", 
"Nic Patterson", "Nicholas Corlett", "Nicholas Floyd", "Nicholas Medina", "Nick", 
"Nick BIschof", "Nick Marien", "Nick Pfundstein", "Nico van Dijk", "Nicolas M. Careau", 
"NightCabbage", "Nightstar", "Nikhil Menon", "Nikolas Craik", "Nina Grimes", 
"Ninospina", "Noah Santoni", "Noah Selzer", "Noah Thoron", "Noelani Blueford", 
"Not_a_Clue", "NovaSilisko", "Nua", "Oliver Bolt", "Olivier", 
"Omarr S. Guerrero", "Omnimental", "Oona Fox", "Orson Cream", "Overand", 
"Owen Mech", "Owen Pedrotti", "P S Dorey", "Paco Pil Pil", "Pacôme Perrotin", 
"Pang Tun Jiang", "ParkerNalchajian", "PaterFrog", "Patrick Anderson", "Patrick Benton", 
"Patrick Bogen", "Patrick Gillan", "Patrick J. Gray", "Patrick Kelley Joyner", "Patrick Merritt", 
"Patrik", "Paul", "Paul Blakey", "Paul DeLaVergne", "Paul Dejean", 
"Paul Hidding", "Paul Keating", "Paul Lewis", "Paul Michael Robison", "Paul Pflugradt", 
"Paul Richard Dinkelmann", "Paul Rutledge", "Paul S-H", "Paul Safford", "Paul Strauss", 
"Paul Vanderwalt", "Paul Watts", "Paul Wright", "Pavel Savchenko", "PawPrint3D", 
"Peace", "Peak", "Per Kristian Ingebrigtsen", "Per-Ingemar Andersson", "Perry R. Cook", 
"Peter", "Peter Froehlich", "Peter Graham", "Peter Kazarian", "Peter Kelly", 
"Peter Kiem", "Peter Trauernicht", "Petr Linhart", "Petroph", "Peyton Seefeldt", 
"Phil Boswell", "Phil Jones", "PhilD", "Philip 'MrPhil' Ludington", "Philip House", 
"Philip Joji", "Philip Trottman", "Philipp Schneider", "Phillip Edwards", "Phillip Pavlovich", 
"Phoebe Danskin", "Photonizer", "Piecewise", "Pieter Leon", "Piotr Michniewski", 
"Pollock McGee", "Polypusher", "Pongrapee Jencharat", "Poz", "Primosz", 
"Procyon", "Pwnytail", "Pyndul", "Qcpu", "Quang Nguyen", 
"Quaxlihuxli", "Quin Kieu", "Quinn Picard", "RIley", "Rachel", 
"Radek Drozdalski", "Radek Dziadkiewicz", "Raffi Thomas", "RagerX", "RainPally", 
"Rakotondratsima", "Raltay", "Randall Joiner", "Randy Walker", "Ray Otto", 
"Raymond Johnson", "Raymond Why", "Reaper1oo", "Rebecca Crabb", "Red The Beard", 
"RedDragonGecko", "Remi D. Finjord", "Remy Dyer", "Rens2Sea", "René H. Thomsen", 
"Rerdburry", "RevenantX", "Richard", "Richard Allen", "Richard Boehme", 
"Richard Cumberland", "Richard Davis", "Richard Edmands", "Richard Gillen", "Richard Hebdon", 
"Richard Hensman", "Richard Knight", "Richard Tomsett", "Richard Tuber", "Richard Walroth", 
"Richard van der Haak", "Rift", "Rin Tuon", "Rob Hamilton", "Rob Jaspersohn", 
"Rob Johnston", "Rob King", "Rob Liddle", "Rob Wilson", "Robb Skeens", 
"Robert", "Robert Ballard", "Robert Bass", "Robert Butler", "Robert Christopher Gouge", 
"Robert Hartshorn", "Robert Hicks", "Robert Horvath", "Robert Iannucci", "Robert Kamphaus II", 
"Robert Mele", "Robert Noll", "Robert Ohannessian", "Robert Shanks", "Robert Sirbu", 
"Robin Nanney", "Robin Sloan", "Roborogue", "Rocky Teruya", "Rodrigo Noronha", 
"Roelant Cornelissen", "Roger Allen", "Rogueleader89", "Rohit", "Ron Hakim", 
"Ron Luhtanen", "Ronique Wright", "Rosemary Cotnoir", "Ross Campbell", "Ross Jensen", 
"Ross McKenzie", "Ross Pearson", "Ross a May", "Russel Crozier", "Ryan", 
"Ryan Barker", "Ryan Benmalek", "Ryan Cramer", "Ryan Flannery", "Ryan Fleming", 
"Ryan Hansen", "Ryan Ledsinger", "Ryan McCafferty", "Ryan Muther", "Ryan Myers", 
"Ryan Rohrer", "Ryan Schultz", "Ryan Slaton", "Ryan Vincent", "Ryder Donahue", 
"Ryzuku", "Sam Botstein", "Sam Cariss", "Sam Courtney", "Sam Douglas", 
"Sam Fox", "Sam Stevens", "Sam Wheeler", "Samaron", "Samuel", 
"Samuel Beresford", "Samuel Coulson", "Samuel Klein", "Samuel Messing", "Sandalphon", 
"Sandra Lenardova", "Sarah Morrison", "Sarnitru", "Sasaki Chasofito", "Sasyn", 
"Schmeisses", "Scorpimonkey", "Scott Bromander - Docix", "Scott Chi", "Scott Cutler", 
"Scott Densmore", "Scott Early", "Scott Galante", "Scott Gregg", "Scott Kullberg", 
"Scott T. Wendelsdorf", "Scott Tarr", "Scott Wilson", "Scroey", "Seamus Moffat", 
"Sean", "Sean Brock", "Sean Buelow", "Sean Claremont", "Sean Coincon", 
"Sean Graham", "Sean Hawkes", "Sean Marzec", "Sebastian  Miller", "Sebastian Eschlböck", 
"Sebastián Vansteenkiste", "Selene O'Rourke", "Seth Pacheco", "Seung Cho", "Seven", 
"Shadowcaster", "Shane", "Shane Cashman", "Shapini", "Shawn Daniels", 
"Shawn E Kelly", "Shawn Erway", "Shawn Price", "ShenaniganNinja", "Shin Jung-Chul", 
"Simon Cassford", "Simon Gilquin", "Simon Soanes", "Sindyr - Seer Elite of Phoenix Rising", "Sir Phillip Tubell", 
"Skiddywinks", "Skjargh", "Skunkoon", "Snapp3r", "Snowcastle Games", 
"Some1", "Sondre Naustdal", "Sophia Pandya", "Sophie Diao", "SpaceEnthusiast", 
"SpartaCraft", "Spencer Case", "Spencer Reeve", "Spyke Alexander", "Staś Małolepszy", 
"Stefan V", "Stephan Vogt", "Stephen", "Stephen Bent and Shannon O'Neil", "Stephen Lemelin", 
"Stephen Michel", "Stephen Perez", "Stephen Williams", "Stephen Zimmerman", "Steve Adams", 
"Steve Chiavelli", "Steve Fontaine", "SteveDav", "Steven Brackney", "Steven Grimm", 
"Steven M Bunnell", "Steven Proctor", "Steven Savage", "Steven Schalek", "Stewart \"Zoot\" Wymer", 
"StressedoutCat", "Stuart Anderson", "Stuart Kim-Brown aka \"Uncle Stu\"", "Stuart Thomson", "Superbun", 
"Sutha Suveeranont", "Søren Jones", "T.J. F.", "TGS", "Tagc", 
"Talon", "Tamir Nadav", "Tamok", "Tara Lynn Kovacs", "Tarq Stutely", 
"Tasgall", "Tate Hobart", "TeHWooF", "Ted Bisson", "TemjinStrife", 
"Terabi", "Terrence Hannon", "Tetsuo Sugiyama", "Teun Leemans", "Tgreny", 
"TheStatPow", "Theeramet Ratsameewijitpaisan", "Theo Setsma", "Theodorik O'Broin", "Thiago Montoya", 
"Thibault Marty", "Thomas Aigner", "Thomas Guppy", "Thomas Hale", "Thomas James Smith", 
"Thomas Jegust", "Thomas Kreuzer", "Thomas Sham", "Thomas Willcox", "Thoune", 
"Tiago Fausto Faucz", "Tien Pham", "TikiBob", "Tim Collison", "Tim DeBenedictis", 
"Tim Mirkes", "Tim Noyce", "Tim Pashley", "Timothy Wilson", "Tingko Hsu", 
"Tobias Gierke", "Toby", "Todd Heflin", "Todd Showalter", "Todd Zircher", 
"Tom", "Tom Buff", "Tom Krausse", "Tom Prats", "Tom Santurri", 
"Tom Withers", "Tomas Almgren", "Tommy Burnette", "Tony Dowler", "Tony Evans", 
"Tony Hamilton", "Tournesol42", "Tracy Barnett/Exploding Rogue Studios", "Travij San Grepo", "Travis Dunbar", 
"Travis Stewart", "Trent DeRoc", "Trey", "Trey Streit", "Tristan Banta", 
"Tristan Vaughan Harold Collins", "Trout", "Troy", "Tucker Chapin", "Tyler", 
"Tyler Cole", "Tyler Ichenberg", "Tyler Molz", "Tyler Schofield", "Tyson Cecka", 
"Tzu Chjeh Wu", "UberPilot", "Uomoz of the Obsidian Order", "Vakey Rujevic", "Vedran Klanac", 
"Vegard Skjefstad", "Venkatesh Srinivas", "Veraetan", "Vingdoloras", "Vintoks", 
"Vinícius Augusto de Souza", "Vladimir", "Vynxar", "Wade Woodson", "Wally", 
"Walter Sellars", "Warhan13", "Wayne Yee", "Weiquan Wu", "Werner Maisl", 
"Wessel Roose", "West_Sage", "WhindGhost8", "Whiskisieppo", "WhiteMagic", 
"Whiterabbit-uk", "Wiccan Hour Inc.", "Will A Kavanagh", "Will Allen", "Will Ke", 
"Will Luongo", "Will Miller", "Will Scott-Cornell", "William E Palmer", "William Goins", 
"William Gross", "William Hallet", "William Jacobson", "William Plumley", "Windsor Bisbee", 
"Wingsofinsanity", "Winterblink", "Wolf", "Wolfenhex", "Wolfy", 
"Wren Hensgen", "Wyatt Foster", "Wytze", "Xargonis", "Xer", 
"Xirfox", "YP Lim", "Yen-Yit Soo", "Yoneo Arai", "Yoonah Danskin", 
"Young Liu", "Yujean Yee", "Zac", "Zach B.", "Zach Lindblad", 
"Zachary Galkin", "Zachary Shovelton", "Zachary Strebeck", "Zaptan", "Zaïdi", 
"Zedster", "Ziryo", "Zombie Sam", "Zpajro", "Zroc", 
"abynormal", "againey", "alexander hayes", "anja", "anonymous", 
"ar73", "arcticSearcher", "arturo", "asmallman98", "bararizun", 
"blep", "bob", "burnt pancake", "burntcustard", "c1h9r9i5s", 
"casal guillaume", "charlie deuser", "chase pashkowich", "chris bliss", "chris flatley", 
"christian hauser", "christian reichelt", "cloud07studios", "darkh", "david", 
"dmchris", "e314", "ehrgeiz", "elaner", "engber", 
"etc", "etien", "flags", "fookolt", "fred_dot_u", 
"frshr (not a bot)", "ghosttie", "helix464", "iforce2d", "jan stiller", 
"jared wilkening", "jeffg10", "jimmyff", "josh", "junkdog", 
"k", "karmajay", "kasper johansen", "kebrus", "kelmer77", 
"kevinzana", "killa", "knaji", "kornholioefx", "lars-göran", 
"lucas brimson", "lukaself", "mark zeman", "martin", "matt", 
"mauva02", "max", "mdidia", "michael addabbo", "michael rigato", 
"mikebert", "ming", "mostlikely", "mukut", "myofsteel", 
"neadlak", "nelson wolfsheimer", "neoquietus", "paul", "penguinpaladin", 
"peous", "phosphoer", "raedeo", "rastrof", "rdnwt", 
"realconker15", "rentheunclean", "ringo", "russell brand", "rylen dreskin", 
"samjaza", "scyleung", "slaytanic", "spencer lehman", "springheeledjak", 
"stephen cartwright", "steven link", "stien", "stuart lees", "thomas haskin", 
"trademark", "trevor", "trisk", "wazzebu", "weiren.", 
"will howard", "xort", "zechs83", "Четверть жизни", "浅井 雅己", 
};
